version: '3'

services:

  listener-service:
    build:
      context: .
      dockerfile: listener/Dockerfile
    environment:
      CONFIG_FILE: config/config.yml
    ports:
      - "3010:3010"
    networks:
      - my_network

  notifier-service:
    build:
      context: .
      dockerfile: notifier/Dockerfile
    environment:
      CONFIG_FILE: config/config.yml
    ports:
      - "3011:3011"
    networks:
      - my_network
  
  nats:
    image: nats
    ports:
      - "4223:4222"
      - "8222:8222"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge