version: '3'

services:

  notifier-service:
    build:
      context: .
      dockerfile: notifier/Dockerfile
    ports:
      - "3011:3011"
    networks:
      - my_network
  
  listener-service:
    build:
      context: .
      dockerfile: listener/Dockerfile
    ports:
      - "3010:3010"
    networks:
      - my_network
  
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge